[profile.default]
evm_version = "prague"
solc_version = "0.8.29"
sort_imports = true
via_ir = true
optimizer = true
optimizer_runs = 200
remappings=[
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
    "solady/=lib/solady/src/"
]

[profile.production]
optimizer = true
optimizer_runs = 100000

# Generate skimmable test docs with command: make docs-test
[profile.testdocs]
src = "test"