[profile.default]
evm_version = "prague"
solc_version = "0.8.29"
sort_imports = true
via_ir = true
optimizer = true
optimizer_runs = 200
remappings=[
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
    "solady/=lib/solady/src/"
]

[profile.production]
optimizer = true
optimizer_runs = 100000

# Generate skimmable test docs with command: make docs-test
[profile.testdocs]
src = "test"

[lint]
lint_on_build = false
exclude_lints = [
    "mixed-case-variable", # *URI variable names
    "mixed-case-function", # *URI function names
    "asm-keccak256", # EIP-712 hashing
    "erc20-unchecked-transfer", # Warning on ERC-721 transferFrom
    "unused-import" # BuilderCodesTest imports for purpose of dependent tests
]

[fmt]
sort_imports = true
wrap_comments = true